In [1]:
import pandas as pd 
import numpy as np

In [2]:
#generating sythetic prediction

np.random.seed(42)

n = 500

confidence = np.random.uniform(0.5, 1.0, n)

true_accuracy = 0.7

correct = np.random.binomial(1, true_accuracy, n)

df = pd.DataFrame({
    "confidence": confidence,
    "correct": correct
})

df.head()

   confidence  correct
0    0.687270        1
1    0.975357        1
2    0.865997        1
3    0.799329        0
4    0.578009        1

In [3]:
df["confidence"] = df["confidence"] + 0.15
df["confidence"] = df["confidence"].clip(0, 1)

df.head()

   confidence  correct
0    0.837270        1
1    1.000000        1
2    1.000000        1
3    0.949329        0
4    0.728009        1

In [5]:
df.to_csv("../sample_data/predictions.csv", index=False)

print("Dataset saved!")

Dataset saved!